[global]
line-length = 100

[MD013]
reflow = true

[MD032]
allow-lazy-continuation = false

[MD033]
allowed-elements = ["details", "summary"]

[MD041]
front-matter-title-pattern = "^(title|header|name):"
