[global]
exclude = [
  "**/scratch-files/**.markdown", # Used by Snacks.nvim
  "/private/**.md", # Used by OpenCode when calling `$EDITOR` to edit the prompt
]
line-length = 100

[MD013]
reflow = true

[MD032]
allow-lazy-continuation = false

[MD033]
allowed-elements = ["details", "summary"]
